steps:
- name: 'python:3.6-alpine'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'python unit_test.py -v'

- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '-t'
  - 'eu.gcr.io/$PROJECT_ID/logicapp:$SHORT_SHA'
  - '.'

- name: 'comarada/envsubst'
  id: Prepare dev enviroment file
  args: ['kub_dev.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'
  
 - name: 'gcr.io/cloud-builders/gsutil'
  id: Push dev K8 manifest to GS bucket
  args: ['cp','ready_kub_dev.yaml','gs://$PROJECT_ID-spinnaker-conf/confman/ready_kub_dev.yaml']
 
images: ['eu.gcr.io/$PROJECT_ID/logicapp:$SHORT_SHA']
