steps:
# This step runs the unit tests on the app
- name: 'python:3.6-alpine'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r ./requirements.txt && python unit_test.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '-t'
  - 'eu.gcr.io/$PROJECT_ID/logicapp:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Docker Image to c-registry
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/logicapp:$SHORT_SHA'

- name: 'supinf/envsubst'
  id: Prepare dev enviroment file
  args: ['kub_dev.yaml','>','kub_dev_new.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'

#file for bucket
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-spinnaker-conf/logicapp/'
    paths: ['kub_dev_new.yaml']

